export const projectsData: ProjectType[] = [
  {
    id: "asdfasdf",
    name: "Website Redesign",
    startDate: "January 1, 2023",
    dueDate: "March 15, 2023",
    status: "Completed",
    priority: "Medium",
    statusColor: "",
    priorityColor: "bg-[#FF9800] text-white",
    milestones: [
      {
        id: "asdfasdf",
        name: "Website Redesign",

        projectName: "Website Redesign",
        dueDate: "March 15, 2023",
        status: "Completed",
        priority: "Medium",
        startDate: "January 1, 2023",
        statusColor: "",
        priorityColor: "bg-[#FF9800] text-white",
        tasks: [
          {
            id: "asdfasdf",
            name: "Design logo",
            status: "Not Started",
            statusColor: "",
            priorityColor: "bg-[#FF9800] text-white",
            dueDate: "March 15, 2023",
            priority: "High",
          },
          {
            id: "asdasd",
            name: "Design logo",
            status: "Not Started",
            dueDate: "March 15, 2023",
            priority: "High",
            statusColor: "",
            priorityColor: "bg-[#FF9800] text-white",
          },
          {
            id: "fghfgh",
            name: "Design logo",
            status: "Not Started",
            dueDate: "March 15, 2023",
            priority: "High",
            statusColor: "",
            priorityColor: "bg-[#FF9800] text-white",
          },
        ],
      },
    ],
  },
  {
    id: "asdfasdfasd",
    name: "E-commerce Platform Setup",
    startDate: "January 1, 2023",
    dueDate: "March 15, 2023",
    status: "In Progress",
    priority: "High",
    statusColor: "text-blue-500",
    priorityColor: "bg-[#F44336]   text-white",
    milestones: [],
  },
  {
    id: "asdfasdfasdasdas",
    name: "Mobile App Development",
    startDate: "January 1, 2023",
    dueDate: "March 15, 2023",
    status: "Not Started",
    priority: "Low",
    statusColor: "text-gray-500",
    priorityColor: "bg-[#FFC107] text-white",
    milestones: [],
  },
];

export const milestones: MilestoneType[] = [
  {
    id: "asdfasdf",

    name: "Website Redesign",
    projectName: "Website Redesign",
    dueDate: "March 15, 2023",
    status: "Completed",
    priority: "Medium",
    startDate: "January 1, 2023",
    statusColor: "",
    priorityColor: "bg-[#FF9800] text-white",
    tasks: [
      {
        id: "asdfasdf",
        name: "Design logo",
        status: "Not Started",
        dueDate: "March 15, 2023",
        priority: "High",
        statusColor: "",
        priorityColor: "bg-[#FF9800] text-white",
      },
      {
        id: "asdasd",
        name: "Design logo",
        status: "Not Started",
        dueDate: "March 15, 2023",
        priority: "High",
        statusColor: "",
        priorityColor: "bg-[#FF9800] text-white",
      },
      {
        id: "fghfgh",
        name: "Design logo",
        status: "Not Started",
        dueDate: "March 15, 2023",
        priority: "High",
        statusColor: "",
        priorityColor: "bg-[#FF9800] text-white",
      },
    ],
  },
  {
    id: "asdfasasdfdf",

    name: "E-commerce Platform Setup",
    projectName: "Website Redesign",
    dueDate: "March 15, 2023",
    startDate: "January 1, 2023",

    status: "In Progress",
    tasks: [],
    priority: "High",
    statusColor: "text-blue-500",
    priorityColor: "bg-[#F44336]   text-white",
  },
  {
    id: "asdfasdfgdfgdf",

    name: "Mobile App Development",
    projectName: "Project 1",
    startDate: "January 1, 2023",
    tasks: [],

    dueDate: "March 15, 2023",
    status: "Not Started",
    priority: "Low",
    statusColor: "text-gray-500",
    priorityColor: "bg-[#FFC107] text-white",
  },
];

export const payments: PaymentType[] = [
  {
    id: "001",
    invoiceId: "#INV-1001",
    project: {
      id: "asdfasdfasdasdas",
      name: "Mobile App Development",
      startDate: "January 1, 2023",
      dueDate: "March 15, 2023",
      status: "Not Started",
      priority: "Low",
      statusColor: "text-gray-500",
      priorityColor: "bg-[#FFC107] text-white",
      milestones: [],
    },
    dateIssued: "2025-01-01",
    dueDate: "2025-01-15",
    status: "Completed",
    price: "5000",
  },
  {
    id: "002",
    invoiceId: "#INV-1002",
    project: {
      id: "asdfasdfasdasdas",
      name: "Mobile App Development",
      startDate: "January 1, 2023",
      dueDate: "March 15, 2023",
      status: "Not Started",
      priority: "Low",
      statusColor: "text-gray-500",
      priorityColor: "bg-[#FFC107] text-white",
      milestones: [],
    },
    dateIssued: "2025-01-10",
    dueDate: "2025-02-05",
    status: "Pending",
    price: "12000",
  },
  {
    id: "003",
    invoiceId: "#INV-1003",
    project: {
      id: "asdfasdfasdasdas",
      name: "Mobile App Development",
      startDate: "January 1, 2023",
      dueDate: "March 15, 2023",
      status: "Not Started",
      priority: "Low",
      statusColor: "text-gray-500",
      priorityColor: "bg-[#FFC107] text-white",
      milestones: [],
    },
    dateIssued: "2025-01-12",
    dueDate: "2025-01-20",
    status: "Completed",
    price: "2500",
  },
  {
    id: "004",
    invoiceId: "#INV-1004",
    project: {
      id: "asdfasdfasdasdas",
      name: "Mobile App Development",
      startDate: "January 1, 2023",
      dueDate: "March 15, 2023",
      status: "Not Started",
      priority: "Low",
      statusColor: "text-gray-500",
      priorityColor: "bg-[#FFC107] text-white",
      milestones: [],
    },
    dateIssued: "2025-01-15",
    dueDate: "2025-02-01",
    status: "Pending",
    price: "20000",
  },
  {
    id: "005",
    invoiceId: "#INV-1005",
    project: {
      id: "asdfasdfasdasdas",
      name: "Mobile App Development",
      startDate: "January 1, 2023",
      dueDate: "March 15, 2023",
      status: "Not Started",
      priority: "Low",
      statusColor: "text-gray-500",
      priorityColor: "bg-[#FFC107] text-white",
      milestones: [],
    },
    dateIssued: "2025-01-05",
    dueDate: "2025-01-25",
    status: "Completed",
    price: "8000",
  },
];
