export const projectsData: ProjectType[] = [
  {
    id: "asdfasdf",
    name: "Website Redesign",
    startDate: "January 1, 2023",
    dueDate: "March 15, 2023",
    status: "Completed",
    priority: "Medium",
    statusColor: "",
    priorityColor: "bg-[#FF9800] text-white",
    milestones: [
      {
        id: "asdfasdf",
        name: "Website Redesign",

        projectName: "Website Redesign",
        dueDate: "March 15, 2023",
        status: "Completed",
        priority: "Medium",
        startDate: "January 1, 2023",
        statusColor: "",
        priorityColor: "bg-[#FF9800] text-white",
        tasks: [
          {
            id: "asdfasdf",
            name: "Design logo",
            status: "Not Started",
            statusColor: "",
            priorityColor: "bg-[#FF9800] text-white",
            dueDate: "March 15, 2023",
            priority: "High",
          },
          {
            id: "asdasd",
            name: "Design logo",
            status: "Not Started",
            dueDate: "March 15, 2023",
            priority: "High",
            statusColor: "",
            priorityColor: "bg-[#FF9800] text-white",
          },
          {
            id: "fghfgh",
            name: "Design logo",
            status: "Not Started",
            dueDate: "March 15, 2023",
            priority: "High",
            statusColor: "",
            priorityColor: "bg-[#FF9800] text-white",
          },
        ],
      },
    ],
  },
  {
    id: "asdfasdfasd",
    name: "E-commerce Platform Setup",
    startDate: "January 1, 2023",
    dueDate: "March 15, 2023",
    status: "In Progress",
    priority: "High",
    statusColor: "text-blue-500",
    priorityColor: "bg-[#F44336]   text-white",
    milestones: [],
  },
  {
    id: "asdfasdfasdasdas",
    name: "Mobile App Development",
    startDate: "January 1, 2023",
    dueDate: "March 15, 2023",
    status: "Not Started",
    priority: "Low",
    statusColor: "text-gray-500",
    priorityColor: "bg-[#FFC107] text-white",
    milestones: [],
  },
];

export const milestones: MilestoneType[] = [
  {
    id: "asdfasdf",

    name: "Website Redesign",
    projectName: "Website Redesign",
    dueDate: "March 15, 2023",
    status: "Completed",
    priority: "Medium",
    startDate: "January 1, 2023",
    statusColor: "",
    priorityColor: "bg-[#FF9800] text-white",
    tasks: [
      {
        id: "asdfasdf",
        name: "Design logo",
        status: "Not Started",
        dueDate: "March 15, 2023",
        priority: "High",
        statusColor: "",
        priorityColor: "bg-[#FF9800] text-white",
      },
      {
        id: "asdasd",
        name: "Design logo",
        status: "Not Started",
        dueDate: "March 15, 2023",
        priority: "High",
        statusColor: "",
        priorityColor: "bg-[#FF9800] text-white",
      },
      {
        id: "fghfgh",
        name: "Design logo",
        status: "Not Started",
        dueDate: "March 15, 2023",
        priority: "High",
        statusColor: "",
        priorityColor: "bg-[#FF9800] text-white",
      },
    ],
  },
  {
    id: "asdfasasdfdf",

    name: "E-commerce Platform Setup",
    projectName: "Website Redesign",
    dueDate: "March 15, 2023",
    startDate: "January 1, 2023",

    status: "In Progress",
    tasks: [],
    priority: "High",
    statusColor: "text-blue-500",
    priorityColor: "bg-[#F44336]   text-white",
  },
  {
    id: "asdfasdfgdfgdf",

    name: "Mobile App Development",
    projectName: "Project 1",
    startDate: "January 1, 2023",
    tasks: [],

    dueDate: "March 15, 2023",
    status: "Not Started",
    priority: "Low",
    statusColor: "text-gray-500",
    priorityColor: "bg-[#FFC107] text-white",
  },
];
